# Generated by Django 4.0.6 on 2022-08-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekpeek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='blog_content',
            field=models.TextField(max_length=16777215),
        ),
    ]
