# Generated by Django 4.0.6 on 2022-08-22 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tekpeek', '0002_alter_data_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='blog_id',
        ),
        migrations.AddField(
            model_name='data',
            name='blog_auth',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='blog_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='blog_short',
            field=models.TextField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='blog_title',
            field=models.TextField(default=django.utils.timezone.now, max_length=65535),
            preserve_default=False,
        ),
    ]
