# Generated by Django 4.0.6 on 2022-08-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekpeek', '0003_remove_data_blog_id_data_blog_auth_data_blog_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='bolg_image',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
