# Generated by Django 4.0.6 on 2022-08-22 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tekpeek', '0004_data_bolg_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='bolg_image',
            new_name='blog_image',
        ),
    ]
