# Generated by Django 4.0.6 on 2022-08-22 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekpeek', '0005_rename_bolg_image_data_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='blog_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
