# Generated by Django 4.0.6 on 2022-08-22 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekpeek', '0006_alter_data_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='blog_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='BLOG DATE'),
        ),
    ]
