# Generated by Django 4.0.6 on 2022-08-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekpeek', '0009_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_title', models.TextField(max_length=200)),
                ('highlight_content', models.TextField(max_length=65535)),
                ('highlight_image', models.ImageField(upload_to='static/dist/assets/img/')),
            ],
        ),
    ]
