# Generated by Django 4.0.6 on 2022-08-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekpeek', '0010_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='blog_image',
            field=models.ImageField(upload_to='static/dist/assets/img/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_link',
            field=models.ImageField(upload_to='static/dist/assets/img/'),
        ),
    ]
