# Generated by Django 4.0.6 on 2022-08-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekpeek', '0011_alter_data_blog_image_alter_news_image_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('script', models.CharField(max_length=256)),
            ],
        ),
    ]
