# Generated by Django 4.0.6 on 2022-08-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tekpeek', '0012_datahandler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataHandler',
        ),
    ]
