# Generated by Django 4.0.6 on 2022-08-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClearTrash',
        ),
    ]
